# Generated by Django 2.2 on 2019-04-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
